import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import ConsentModal from "./components/consent-modal";
import Link from "next/link";
import { NextIntlClientProvider, useTranslations } from "next-intl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const t = useTranslations();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
        <ConsentModal />
          {children}
          <div className="container py-4 d-flex flex-column align-items-center">
            <hr />
            <nav>
              <Link href="/">{t('home')}</Link> |{" "}
              <Link href="/rules">{t('terms_and_conditions')}</Link> |{" "}
              <Link href="/suggestions">{t('suggestions')}</Link> |{" "}
              <a href="mailto:someone@example.com">mail@info.com</a>
            </nav>
            <i>@ www.mypage.com</i>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
